import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { ReportsService } from 'src/app/services/reports.service';
import { StandardDatePipe } from 'src/app/pipes/standard-date.pipe';


const routes: Routes = [
  { path: 'profit', loadComponent: () => import('./profit/profit.component').then(c => c.ProfitComponent) },
  { path: 'profitSummary', loadComponent: () => import('./profit-summary-report/profit-summary-report.component').then(c => c.ProfitSummaryReportComponent) },
  { path: 'membershipsIncome', loadComponent: () => import('./memberships-income-report/memberships-income-report.component').then(c => c.MembershipsIncomeReportComponent) },
  { path: 'privateMembershipsIncome', loadComponent: () => import('./private-memberships-income-report/private-memberships-income-report.component').then(c => c.PrivateMembershipsIncomeReportComponent) },
  { path: 'medicalMembershipsIncome', loadComponent: () => import('./medical-memberships-income-report/medical-memberships-income-report.component').then(c => c.MedicalMembershipsIncomeReportComponent) },
  { path: 'memberships/:type', loadComponent: () => import('./memberships-report/memberships-report.component').then(c => c.MembershipsReportComponent) },
  { path: 'packagesUntil', loadComponent: () => import('./packages-utilization-report/packages-utilization-report.component').then(c => c.PackagesUtilizationReportComponent) },
  { path: 'daybydayprofit', loadComponent: () => import('./daybyday-profit/daybyday-profit.component').then(c => c.DaybydayProfitComponent) },
  { path: 'birthdays', loadComponent: () => import('./birthdays-report/birthdays-report.component').then(c => c.BirthdaysReportComponent) },
  { path: 'callsSummary', loadComponent: () => import('./call-summary-report/call-summary-report.component').then(c => c.CallSummaryReportComponent) },
  { path: 'inactiveMembers', loadComponent: () => import('./not-active-members/not-active-members.component').then(c => c.NotActiveMembersComponent) },
  { path: 'overAttendance', loadComponent: () => import('./over-attendance-report/over-attendance-report.component').then(c => c.OverAttendanceReportComponent) },
  { path: 'debts', loadComponent: () => import('./debts-report/debts-report.component').then(c => c.DebtsReportComponent) },
  { path: 'salesCommission', loadComponent: () => import('./sales-commission-report/sales-commission-report.component').then(c => c.SalesCommissionReportComponent) },
  { path: 'trainerCommission', loadComponent: () => import('./trainer-commission-report/trainer-commission-report.component').then(c => c.TrainerCommissionReportComponent) },
  { path: 'logs', loadComponent: () => import('./logs-report/logs-report.component').then(c => c.LogsReportComponent) },
  { path: 'absent-members', loadComponent: () => import('./absent-members-report/absent-members-report.component').then(c => c.AbsentMembersReportComponent) },
  { path: 'deletedReceipts', loadComponent: () => import('./deleted-receipts-report/deleted-receipts-report.component').then(c => c.DeletedReceiptsReportComponent) },
  { path: 'classesTypes', loadComponent: () => import('./Classes/classes-types-report/classes-types-report.component').then(c => c.ClassesTypesReportComponent) },
  { path: 'heldClasses', loadComponent: () => import('./Classes/held-classes-report/held-classes-report.component').then(c => c.HeldClassesReportComponent) },
  { path: 'instructorDueAmount', loadComponent: () => import('./Classes/instructor-due-amount-report/instructor-due-amount-report.component').then(c => c.InstructorDueAmountReportComponent) },
  { path: 'classesPerInstructorType', loadComponent: () => import('./Classes/classes-per-instructor-type-report/classes-per-instructor-type-report.component').then(c => c.ClassesPerInstructorTypeReportComponent) },
  { path: 'classesBookingList', loadComponent: () => import('./Classes/classes-booking-list-report/classes-booking-list-report.component').then(c => c.ClassesBookingListReportComponent) },
  { path: 'cancelledClasses', loadComponent: () => import('./Classes/cancelled-classes-report/cancelled-classes-report.component').then(c => c.CancelledClassesReportComponent) },
  { path: 'membersAttendanceOnClasses', loadComponent: () => import('./Classes/member-reservations-report/member-reservations-report.component').then(c => c.MemberReservationsOnClassesReportComponent) },
  { path: 'memberAttendance', loadComponent: () => import('./member-attendance-report/member-attendance-report.component').then(c => c.MemberAttendanceReportComponent) },
  { path: 'blockedMembers', loadComponent: () => import('./blocked-members-report/blocked-members-report.component').then(c => c.BlockedMembersReportComponent) },
  { path: 'members', loadComponent: () => import('./members-report/members-report.component').then(c => c.MembersReportComponent) },
  { path: 'lostItems', loadComponent: () => import('./lost-items-report/lost-items-report.component').then(c => c.LostItemsReportComponent) },
  { path: 'benefitsConsumption', loadComponent: () => import('./benefits-consumption-report/benefits-consumption-report.component').then(c => c.BenefitsConsumptionReportComponent) },
  { path: 'invitationCount', loadComponent: () => import('./invitation-count-report/invitation-count-report.component').then(c => c.InvitationCountReportComponent) },
  { path: 'freeConsumedBenefits', loadComponent: () => import('./free-consumed-benefits-report/free-consumed-benefits-report.component').then(c => c.FreeConsumedBenefitsReportComponent) },
  { path: 'staffPayroll', loadComponent: () => import('./employee-payroll-report/employee-payroll-report.component').then(c => c.EmployeePayrollReportComponent) },
  { path: 'gymAttendanceCount', loadComponent: () => import('./Classes/gym-attendance-count-report/gym-attendance-count-report.component').then(c => c.GymAttendanceCountReportComponent) },
  { path: 'membershipTransfer', loadComponent: () => import('./membership-transfer-report/membership-transfer-report.component').then(c => c.MembershipTransferReportComponent) },
  { path: 'customPackagesCommission', loadComponent: () => import('./package-commission-report/package-commission-report.component').then(c => c.PackageCommissionReportComponent) },
  { path: 'topActiveMembers', loadComponent: () => import('./top-active-members-report/top-active-members-report.component').then(c => c.TopActiveMembersReportComponent) },
  { path: 'membershipsDiscount', loadComponent: () => import('./memberships-discount-report/memberships-discount-report.component').then(c => c.MembershipsDiscountReportComponent) },
  { path: 'trainersAchievement', loadComponent: () => import('./trainers-achievement-report/trainers-achievement-report.component').then(c => c.TrainersAchievementReportComponent) },
  { path: 'maximumExpirationDate', loadComponent: () => import('./maximum-expiration-date-report/maximum-expiration-date-report.component').then(c => c.MaximumExpirationDateReportComponent) },
  { path: 'packageUtilizationPerSalesPersonal', loadComponent: () => import('./package-utilization-per-sales-personal-report/package-utilization-per-sales-personal-report.component').then(c => c.PackageUtilizationPerSalesPersonalReportComponent) },
  { path: 'consumedPTSessions', loadComponent: () => import('./consumed-pt-sessions-report/consumed-pt-sessions-report.component').then(c => c.ConsumedPTSessionsReportComponent) },
  { path: 'membershipUpgrade', loadComponent: () => import('./membership-upgrade-report/membership-upgrade-report.component').then(c => c.MembershipUpgradeReportComponent) },
  { path: 'expenses', loadComponent: () => import('./expenses-report/expenses-report.component').then(c => c.ExpensesReportComponent) },
  { path: 'employeeFinancial', loadComponent: () => import('./employee-financial-report/employee-financial-report.component').then(c => c.EmployeeFinancialReportComponent) },
  { path: 'consumedPTSessionsPerMembership', loadComponent: () => import('./consumed-pt-sessions-per-membership-report/consumed-pt-sessions-per-membership-report.component').then(c => c.ConsumedPTSessionsPerMembershipReportComponent) },
  { path: 'consumedPTSessionsPerTrainer', loadComponent: () => import('./consumed-pt-sessions-per-trainer-report/consumed-pt-sessions-per-trainer-report.component').then(c => c.ConsumedPTSessionsPerTrainerReportComponent) },
  { path: 'trainerClosingRatioDetails', loadComponent: () => import('./trainer-closing-ratio-details-report/trainer-closing-ratio-details-report.component').then(c => c.TrainerClosingRatioDetailsReportComponent) },
  { path: 'trainerClosingRatio', loadComponent: () => import('./trainer-closing-ratio-report/trainer-closing-ratio-report.component').then(c => c.TrainerClosingRatioReportComponent) },
  { path: 'salesPersonClosingRatioDetails', loadComponent: () => import('./sales-person-closing-ratio-details-report/sales-person-closing-ratio-details-report.component').then(c => c.SalesPersonClosingRatioDetailsReportComponent) },
  { path: 'salesPersonClosingRatio', loadComponent: () => import('./sales-person-closing-ratio-report/sales-person-closing-ratio-report.component').then(c => c.SalesPersonClosingRatioReportComponent) },
  { path: 'multipleAttendancePerDay', loadComponent: () => import('./multiple-attendance-per-day-report/multiple-attendance-per-day-report.component').then(c => c.MultipleAttendancePerDayReportComponent) },
  { path: 'fixedTrainerCommission', loadComponent: () => import('./fixed-trainer-commission-report/fixed-trainer-commission-report.component').then(c => c.FixedTrainerCommissionReportComponent) },
  { path: 'trainer-member-retention', loadComponent: () => import('./trainer-member-reten-report/trainer-member-reten-report.component').then(c => c.TrainerMemberRetenReportComponent) },
  { path: 'membershipsIncomePerPackageType', loadComponent: () => import('./memberships-income-per-package-type-report/memberships-income-per-package-type-report.component').then(c => c.MembershipsIncomePerPackageTypeReportComponent) },
  { path: 'freePrivateTraining', loadComponent: () => import('./free-private-training-report/free-private-training-report.component').then(c => c.FreePrivateTrainingReportComponent) },
  { path: 'instructors-payroll', loadComponent: () => import('./Classes/instructor-payroll-report/instructor-payroll-report.component').then(c => c.InstructorPayrollReportComponent) },
  { path: 'instructors-classes-payroll', loadComponent: () => import('./Classes/instructor-payroll-report/payroll-classes-grouped/payroll-classes-grouped.component').then(c => c.PayrollClassesGroupedComponent) },
  { path: 'packagesUntil/:id', loadComponent: () => import('./single-package-utilization-report/single-package-utilization-report.component').then(c => c.SinglePackageUtilizationReportComponent) },
  { path: 'other-entities-bookings', loadComponent: () => import('./Classes/other-entities-bookings-report/other-entities-bookings-report.component').then(c => c.OtherEntitiesBookingsReportComponent) },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  providers: [ReportsService, StandardDatePipe]
})
export class ReportsRoutingModule { }
